name: flash_share
description: A modern offline file sharing application.
publish_to: 'none'
version: 5.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core Logic
  flutter_riverpod: ^2.5.1
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0
  network_info_plus: ^5.0.1
  permission_handler: ^11.3.0
  file_picker: ^8.0.0
  wakelock_plus: ^1.2.0
  path: ^1.9.0
  archive: ^3.6.1
  path_provider: ^2.1.2
  device_apps: ^2.2.0
  uuid: ^4.2.1
  shared_preferences: ^2.2.0
  # flutter_pdfview: ^1.3.2  #  To render PDFs on the phone
  pdfrx: ^1.0.49  # Professional Cross-Platform PDF Engine (Windows/Android/iOS)
  # Persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  
  # For Phone Clone (Photos, Videos, Audio & Contacts)
  photo_manager: ^3.0.0 
  flutter_contacts: ^1.1.9

  # Web & Server features
  mime: ^1.0.4
  shelf_multipart: ^1.0.0
  url_launcher: ^6.2.1
  android_intent_plus: ^5.1.0

  # UI & Aesthetics
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  qr_flutter: ^4.1.0
  glassmorphism_ui: ^0.3.0
  phosphor_flutter: ^1.0.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.5.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/first.png"
  adaptive_icon_foreground: "assets/icon/fg.png"
  adaptive_icon_background: "assets/icon/bg.png"
  adaptive_icon_monochrome: "assets/icon/monochrome.png"

flutter:
  uses-material-design: true